org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
fabric_version=0.140.0+1.21.11

# Mod Properties
mod_name=stitch
archives_base_name=stitch
mod_version=1.4.0-alpha
maven_group=io.github.fourmisain
