org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.10
fabric_version=0.114.0+1.21.3

# Mod Properties
mod_name=stitch
archives_base_name=stitch
mod_version=1.3.0-alpha
maven_group=io.github.fourmisain
