org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
fabric_version=0.133.14+1.21.9

# Mod Properties
mod_name=stitch
archives_base_name=stitch
mod_version=1.4.0-alpha
maven_group=io.github.fourmisain
