import static groovy.json.JsonOutput.*


plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
}

repositories {
	maven {
		url 'https://maven.terraformersmc.com/releases'
	}
	maven {
		url 'https://raw.githubusercontent.com/SolidBlock-cn/mvn-repo/main'
	}
	flatDir { dir "." }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	include implementation(project(path: ":stitch", configuration: 'namedElements'))
	modImplementation "pers.solid:brrp-fabric:${brrp_version}"
}

subprojects {
	apply plugin: 'fabric-loom'
}

allprojects {
	version = project.mod_version + '-' + minecraft_version
	group = project.maven_group

	base {
		archivesName = project.archives_base_name
	}

	processResources {
		// expand all properties from gradle.properties
		def stringProperties = project.properties.findAll { it.value instanceof String }
		stringProperties.each { inputs.property(it.key, it.value) }

		['*.mod.json', '*.mixins.json'].each {
			filesMatching(it) {
				expand(stringProperties) {
					escapeBackslash = true
				}
			}
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.compilerArgs.add('-Xlint:deprecation')
		it.options.release = project.java_version as Integer
	}

	java {
		targetCompatibility = sourceCompatibility = project.java_version as Integer
		withSourcesJar()
	}

	jar {
		from("LICENSE") {
			rename { "${it}_${project.base.archivesName.get()}" }
		}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
