plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

loom {
	accessWidenerPath = file("src/main/resources/dirtnt.accesswidener")

	runs {
		client {
			vmArgs "-Dmixin.debug.export=true"
			programArgs "--username", "Test"
		}
	}
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	maven {
		url = 'https://maven.terraformersmc.com/releases'
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	api project(path: ":stitch", configuration: 'namedElements')
	include project(":stitch")
}

subprojects {
	apply plugin: 'fabric-loom'
}

allprojects {
	version = project.mod_version + '-' + minecraft_version
	group = project.maven_group

	base {
		archivesName = project.archives_base_name
	}

	processResources {
		// expand all properties from gradle.properties
		def stringProperties = project.properties.findAll { it.value instanceof String }
		inputs.properties(stringProperties)

		filesMatching(['*.mod.json', '*.mixins.json']) {
			expand(stringProperties) {
				escapeBackslash = true
			}
		}
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.compilerArgs.add('-Xlint:deprecation')
		it.options.release = project.java_version as Integer
	}

	java {
		targetCompatibility = sourceCompatibility = project.java_version as Integer
		withSourcesJar()
	}

	jar {
		inputs.property "archivesName", project.base.archivesName

		from("LICENSE") {
			rename { "${it}_${inputs.properties.archivesName}" }
		}
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
