org.gradle.jvmargs=-Xmx2G
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.152.1+26.2

# Mod Properties
mod_version=1.8.1
maven_group=fourmisain
archives_base_name=DirTNT

java_version=25

fabric_loader_version_range=>=0.18.5
fabric_api_version_range=>=0.145.0
game_version_range=>=26.2
